[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd backend && npm ci"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate"
]

[start]
cmd = "cd backend && npx ts-node --transpile-only src/index.ts"

[variables]
NODE_ENV = "production"